apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-postgresql-data-disk
  labels:
    name: gitlab-postgresql-data-disk
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: "gitlab-postgresql-data-disk"
    fsType: "ext4"
