apiVersion: v1
kind: Service
metadata:
  namespace: gitlab
  name: gitlab
  labels:
    name: gitlab
spec:
  type: LoadBalancer  # Provide an external IP
  selector:
    name: gitlab
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: ssh
    port: 22
    targetPort: ssh
