apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gitlab
  name: gitlab-postgresql
spec:
  replicas: 1
  template:
    metadata:
      name: gitlab-postgresql
      labels:
        name: gitlab-postgresql
    spec:
      containers:
      - name: postgresql
        image: sameersbn/postgresql:9.5-3
        env:
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: passw0rd
        - name: DB_NAME
          value: gitlab_production
        - name: DB_EXTENSION
          value: pg_trgm
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
        emptyDir: {}
