apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-disk
  labels:
    name: gitlab-data-disk
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: "gitlab-data-disk"
    fsType: "ext4"
